"""Dump the running Live's Python API to docs/live-api/ (developer tool).

Asks the Remote Script's ``dump_live_api`` command for every class and member
of the ``Live`` module, with the Boost.Python docstrings (which carry the
signatures), and writes one JSON file per module plus an ``index.md``
overview. The output describes the user's own Live build, so it is gitignored.

Usage: ``ableton-mcp-dump-live-api [--out DIR] [--host H] [--port P] [--module NAME ...]``
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from pathlib import Path
from typing import Any, Callable, Iterable

SendCommand = Callable[..., Any]


class DumpError(Exception):
    """A failure the command line reports as a message and non-zero exit."""


def _safe_name(name: str) -> str:
    """Keep a module or version name usable as a single path component."""
    cleaned = re.sub(r"[^A-Za-z0-9._-]", "_", str(name)).strip(".")
    return cleaned or "unknown"


def _version_string(live_version: Any) -> str:
    if isinstance(live_version, dict):
        if live_version.get("string"):
            return str(live_version["string"])
        parts = [live_version.get(k) for k in ("major", "minor", "bugfix")]
        if all(p is not None for p in parts):
            return ".".join(str(p) for p in parts)
    return "unknown"


def _first_line(doc: Any) -> str:
    if not doc:
        return ""
    for line in str(doc).splitlines():
        if line.strip():
            return line.strip()
    return ""


def _md_cell(text: str) -> str:
    return text.replace("|", "\\|")


def _call(send_command: SendCommand, params: dict[str, Any]) -> dict[str, Any]:
    try:
        result = send_command("dump_live_api", params)
    except Exception as e:
        if getattr(e, "code", None) == "unknown_command":
            raise DumpError(
                "The loaded Ableton Remote Script has no dump_live_api command. "
                "Run `ableton-mcp-install-script`, then restart Ableton Live."
            ) from e
        raise DumpError(f"dump_live_api failed: {e}") from e
    if not isinstance(result, dict):
        raise DumpError(f"dump_live_api returned unexpected data: {result!r}")
    return result


def render_index(version: str, dumps: list[dict[str, Any]]) -> str:
    lines = [
        f"# Live API — Live {version}",
        "",
        "Generated by `ableton-mcp-dump-live-api` from the running Live. "
        "The first docstring line is where Boost.Python puts the signature.",
        "",
    ]
    for dump in dumps:
        lines += [f"## {dump.get('module')}", ""]
        classes = dump.get("classes") or {}
        for class_name in sorted(classes):
            cls = classes[class_name] or {}
            lines += [f"### {class_name}", ""]
            class_doc = _first_line(cls.get("doc"))
            if class_doc:
                lines += [class_doc, ""]
            members = cls.get("members") or {}
            if not members:
                lines += ["_No members._", ""]
                continue
            lines += ["| Name | Kind | Doc |", "|---|---|---|"]
            for name in sorted(members):
                member = members[name] or {}
                lines.append(
                    f"| `{_md_cell(name)}` | {_md_cell(str(member.get('kind') or ''))} "
                    f"| {_md_cell(_first_line(member.get('doc')))} |"
                )
            lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def dump_live_api(send_command: SendCommand, out_dir: Path,
                  modules: Iterable[str] | None = None) -> Path:
    """Fetch the API dump and write it under ``out_dir/<version>/``.

    Returns the directory written. Raises DumpError on failure.
    """
    overview = _call(send_command, {})
    available = list(overview.get("modules") or [])
    wanted = list(modules) if modules else available
    unknown = [m for m in wanted if m not in available]
    if unknown:
        raise DumpError(
            f"Unknown module(s): {', '.join(unknown)}. "
            f"Available: {', '.join(available) or 'none'}"
        )

    version = _version_string(overview.get("live_version"))
    target = Path(out_dir) / _safe_name(version)
    target.mkdir(parents=True, exist_ok=True)

    dumps = []
    for module in wanted:
        dump = _call(send_command, {"module": module})
        dumps.append(dump)
        path = target / f"{_safe_name(module)}.json"
        path.write_text(json.dumps(dump, indent=2, sort_keys=True) + "\n",
                        encoding="utf-8")

    (target / "index.md").write_text(render_index(version, dumps), encoding="utf-8")
    return target


def _default_connect(host: str, port: int):
    from .server import AbletonConnection

    connection = AbletonConnection(host=host, port=port)
    if not connection.connect():
        raise DumpError(
            f"Could not connect to Ableton at {host}:{port}. Is Live running "
            "with the AbletonMCP Remote Script selected as a Control Surface?"
        )
    return connection


def main(argv: list[str] | None = None, connect=None) -> int:
    parser = argparse.ArgumentParser(
        prog="ableton-mcp-dump-live-api",
        description="Write the running Live's Python API to JSON and Markdown.",
    )
    parser.add_argument("--out", default=None,
                        help="Output directory (default: ./docs/live-api)")
    parser.add_argument("--host", default=os.environ.get("ABLETON_HOST", "localhost"))
    parser.add_argument("--port", type=int,
                        default=int(os.environ.get("ABLETON_PORT", "9877")))
    parser.add_argument("--module", action="append", dest="modules", default=None,
                        help="Only dump this Live module (repeatable; default: all)")
    args = parser.parse_args(argv)

    out_dir = Path(args.out) if args.out else Path.cwd() / "docs" / "live-api"
    connect = connect or _default_connect

    connection = None
    try:
        connection = connect(args.host, args.port)
        target = dump_live_api(connection.send_command, out_dir, args.modules)
    except DumpError as e:
        print(f"error: {e}", file=sys.stderr)
        return 1
    except Exception as e:
        print(f"error: could not reach Ableton at {args.host}:{args.port}: {e}",
              file=sys.stderr)
        return 1
    finally:
        if connection is not None and hasattr(connection, "disconnect"):
            connection.disconnect()

    print(f"Wrote Live API dump to {target}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
